Mac v56 release almost ready (#295)...
Fixes to examples and build tools on Mac.

Update to CEF 3.2924.1575.g97389a9 on Mac.

Support automate.py --prebuilt-cef on Mac.

Fix qt4.py example on Mac.
Rename qt.py to qt4.py.

Fix gtk2.py example on Mac.
On Mac the gtk2.py example forces CEF message loop by default.

You can enable debug information in all examples by passing
--debug flag. Added info to KB.

Add instructions on how to debug "segmentation fault" crash
on Linux and Mac in the Knowledge Base document.

Update all examples to add detailed notes about clearing all
browser references for CEF to shutdown cleanly.

Rename build_module.py tool to cython_setup.py.

Enhance sudo detection in build.py.

Increase time for message loop to 1 sec, otherwise tests
sometimes fail with error:
> AssertionError: Check assert:
> LoadHandler.FrameSourceVisitor_True

Create API.md document which links to root api/ directory.

Enhance linking in api/ reference, in top headers
and in API index.